### ISSUE TITLE
.NET core demo application

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET#45]
This issue is raised here https://forum.groupdocs.com/t/editor-sample-net-core-project/12614
Hi,
Just like there's a Viewer .NET core demo UI application https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET/tree/master/Demos/ASP.NET%20Core, can you please make one for GroupDocs.Editor (without Angular)?
Thanks

**Comment by stupakviktor** [comment]
Most relevant existing samples you can find here https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-UI/tree/master/samples also see how to use GroupDocs.Editor - https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-UI/wiki
