### ISSUE TITLE
GroupDocs.Editor UI sample using jQuery

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-editor/GroupDocs.Editor-for-.NET#46]
This is requested at https://forum.groupdocs.com/t/unable-to-view-document-in-word-editor-properly/14453/6
Hi,
Could you please create a simple jQuery application that demonstrates the basics of GroupDocs.Editor API.
Existing UI projects are developed using Angular. 

Thanks

**Comment by stupakviktor** [comment]
Hi, @atirtahirgroupdocs  we prepare sample with jQuery see more https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-UI/tree/master/samples/GroupDocs.Editor.UI.JQueryMVCSample + how to call GroupDocs.Editor RESTful for .NET via jQuery - https://github.com/groupdocs-editor/GroupDocs.Editor-for-.NET-UI/wiki
